### ISSUE TITLE
VCS directory present: .git

### ISSUE THREAD

**Issue by chorny** [lucas1/Dancer2-Plugin-Pg#1]
You accidentally packed your repository into distribution. It takes space in CPAN mirrors. Please remove it.
Build tool for LUCAS/Dancer2-Plugin-Pg-0.04.tar.gz was detected as Module::Build.
To remove repository directory you need to:
- Upgrade Module::Build and ExtUtils::Manifest to latest version.
- Remove .git directory and any files in it from MANIFEST and add regex for .git to MANIFEST.SKIP (if exists).
- Create your distribution for CPAN with your build tool: `Build dist`.
- Delete old versions from PAUSE, especially versions listed here: http://cpanold.chorny.net/?a=LUCAS

P.S. This report was generated automatically.

**Comment by lucas1** [comment]
solved
